const urlSearch = "https://api.themoviedb.org/3/search/movie?api_key=46829fa1f677f290fd75025af8b47e21&query=a%20family%20affair"
const movieSearch = {
    "page": 1,
    "results": [
      {
        "adult": false,
        "backdrop_path": "/ngLxW9WqQAkTCBTcjOSt2Pnz5qZ.jpg",
        "genre_ids": [10749, 35],
        "id": 987686,
        "original_language": "en",
        "original_title": "A Family Affair",
        "overview": "The only thing worse than being the assistant to a high-maintenance movie star who doesn't take you seriously? Finding out he's smitten with your mom.",
        "popularity": 172.586,
        "poster_path": "/l0CaVyqnTsWwNd4hWsrLNEk1Wjd.jpg",
        "release_date": "2024-06-27",
        "title": "A Family Affair",
        "video": false,
        "vote_average": 6.487,
        "vote_count": 38
      },
      {
        "adult": false,
        "backdrop_path": "/tjOPCkjaGPOTe6YeTC9E0Py7KBd.jpg",
        "genre_ids": [18, 35],
        "id": 632000,
        "original_language": "en",
        "original_title": "A Family Affair",
        "overview": "A woman makes a powerful connection with a surprising stranger on her 30th birthday.",
        "popularity": 7.434,
        "poster_path": "/4o7oOzAzFi7wMf40HdqM6YtSzE4.jpg",
        "release_date": "2019-06-20",
        "title": "A Family Affair",
        "video": false,
        "vote_average": 9,
        "vote_count": 1
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [99],
        "id": 323551,
        "original_language": "el",
        "original_title": "A Family Affair",
        "overview": "An Inspirational film about the power of family and music, told through the lives if Greece's most famous musical clan, from the island of Crete. The film captures the Xylouris family at crossroads: fifty - year old Giorgis performs non-stop to satisfy his passionate fans, while his Australian wife and manager Shelagh, struggles to keep the family together. Their three children find new freedom abroad, but struggle to uphold the music of their homeland, while finding their own voice. 'A Family Affair' reveals how this age-old and little known musical tradition is passed on from father to son to grandchildren. it brings to light the redemptive but also obstructive power of a strong family, while bringing us closer to the intimate process of the creation of music.",
        "popularity": 2.24,
        "poster_path": "/gK1n09EriIpZzyjjiARP6Ne5tYh.jpg",
        "release_date": "2015-01-08",
        "title": "A Family Affair",
        "video": false,
        "vote_average": 7,
        "vote_count": 1
      },
      {
        "adult": false,
        "backdrop_path": "/i2fVbAyZvIIy1OKXyHcgNxUpyh4.jpg",
        "genre_ids": [35],
        "id": 155751,
        "original_language": "en",
        "original_title": "A Family Affair",
        "overview": "Judge Hardy faces problems at work and at home. Powerful men in town are upset with his decisions and want to see him impeached; his daughters, Joan and Marion, have romantic problems; and his son, Andy discovers Polly Benedict. As usual, Judge Hardy is concerned with everyone in the family and lends wisdom and calmness to all.",
        "popularity": 6.388,
        "poster_path": "/u3MxoeLXlnPX6xQNL5QVXn24Pjp.jpg",
        "release_date": "1937-03-12",
        "title": "A Family Affair",
        "video": false,
        "vote_average": 5.7,
        "vote_count": 14
      },
      {
        "adult": false,
        "backdrop_path": "/5i0nTCnGBVF3A3WpydhjMT5lsqJ.jpg",
        "genre_ids": [35],
        "id": 1272480,
        "original_language": "en",
        "original_title": "A Family Affair",
        "overview": "A cash-strapped hotel manager is forced to stave off interest from wealthy buyers at a public auction whilst hosting his in-laws on their wedding anniversary.",
        "popularity": 5.729,
        "poster_path": "/fwQU9Ud2djI3Wst0rA5fBjDaL4B.jpg",
        "release_date": "2024-05-20",
        "title": "A Family Affair",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      },
      {
        "adult": false,
        "backdrop_path": "/pNfHEdXHBRnkqb7fAycKck2d3Z9.jpg",
        "genre_ids": [18],
        "id": 449349,
        "original_language": "cn",
        "original_title": "全家福",
        "overview": "To get their parents back together, two clever siblings team up with their grandpa in a series of mischievous antics.",
        "popularity": 9.006,
        "poster_path": "/dGxtZfSTQm4vW1xOZwyHO0WALpz.jpg",
        "release_date": "1984-08-15",
        "title": "A Family Affair",
        "video": false,
        "vote_average": 7.8,
        "vote_count": 4
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [35, 16],
        "id": 989337,
        "original_language": "en",
        "original_title": "A Family Affair",
        "overview": "Krazy Kat follows Ignatz Mouse and thinks about family as the latter takes his children out on a walk.",
        "popularity": 4.052,
        "poster_path": "/m8wRnMnwQ8X23yVF4OJ4gem7l7f.jpg",
        "release_date": "1920-10-25",
        "title": "A Family Affair",
        "video": false,
        "vote_average": 5,
        "vote_count": 1
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [27],
        "id": 947797,
        "original_language": "en",
        "original_title": "A Family Affair",
        "overview": "A family in an isolated cabin are visited by a drifter seeking shelter from a winter storm raging through the night.",
        "popularity": 3.499,
        "poster_path": "/zMUlpNrG2uspJah7gJA6EMQ3MEe.jpg",
        "release_date": "2022-03-25",
        "title": "A Family Affair",
        "video": false,
        "vote_average": 6.5,
        "vote_count": 2
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [35],
        "id": 699691,
        "original_language": "en",
        "original_title": "A Family Affair",
        "overview": "Incidental to the business of getting married and living scrappily ever after, Charlie and Louise are engaged on a flivver jaunt. Charlie has invited Louise along, never dreaming that she would invite the family. But the girl has asked dad, and dad asks mother, and mother invites grandpa and grandma, and they in turn invite the children.",
        "popularity": 2.167,
        "poster_path": null,
        "release_date": "1921-12-14",
        "title": "A Family Affair",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [10749, 18],
        "id": 71249,
        "original_language": "en",
        "original_title": "A Family Affair",
        "overview": "Rachel flees NYC after another traumatic breakup and arrives at her parents' home in San Diego. They are adamant to see their wayward daughter settle down with a nice girl. Rachel goes on several blind dates that misfire badly. She finally lets her mother set her up with Christine, a typical Californian girl. Much to Rachel's chagrin, mom is right! Meanwhile, Rachel's friends wait for her to screw up the relationship. They know, even if she won't admit it, that she still carries a torch for her ex-girlfriend and they're not sure what would happen if she reappeared to reclaim Rachel.",
        "popularity": 4.828,
        "poster_path": "/aXd374qUMlD3ObPVT9b0ez6OIX5.jpg",
        "release_date": "2001-02-14",
        "title": "A Family Affair",
        "video": false,
        "vote_average": 4.9,
        "vote_count": 9
      },
      {
        "adult": false,
        "backdrop_path": "/AvM74ez74Tp2hh0xh9HeSeWrMxR.jpg",
        "genre_ids": [99],
        "id": 366752,
        "original_language": "en",
        "original_title": "A Family Affair",
        "overview": "Tom, the filmmaker, receives a letter from South Africa. His long forgotten 95-year old grandmother Mariann, asks him to come and help her with her will. Tom sets off to South Africa and decides to bring his camera. This starts a journey for the filmmaker and his grandmother, looking back at her life and trying to understand his own.",
        "popularity": 1.626,
        "poster_path": "/gGgh3fCKCYvZ3r02ptI0oYHHshg.jpg",
        "release_date": "2015-11-19",
        "title": "A Family Affair",
        "video": false,
        "vote_average": 5.3,
        "vote_count": 15
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [10770],
        "id": 357824,
        "original_language": "en",
        "original_title": "Cody: A Family Affair",
        "overview": "Cody and Fiorelli try to catch diamond smugglers, but the gems are not where they were supposed to be. Cody embarks to infiltrate the dealers who brought the diamonds in from South Africa. He also searches for a missing teenager.",
        "popularity": 4.98,
        "poster_path": null,
        "release_date": "1994-06-05",
        "title": "Cody: A Family Affair",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [18],
        "id": 878601,
        "original_language": "en",
        "original_title": "A Small Family Affair",
        "overview": "On her wedding day the bride-to-be finds out a well-kept family secret about her heritage that threatens to derail her entire wedding and puts into question the relationship with her long-estranged brother.",
        "popularity": 3.157,
        "poster_path": "/8Mla2lZd3mrblFBpUJcdWwllMnW.jpg",
        "release_date": "2020-11-06",
        "title": "A Small Family Affair",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [99, 35],
        "id": 686862,
        "original_language": "en",
        "original_title": "Robin Williams: A Family Affair",
        "overview": "The cast and crew of RV (2006) comment on how Robin Williams is \"always on,\"  \"amazingly brilliantly talented,\" and  \"the sweetest guy to work with.\"",
        "popularity": 2.21,
        "poster_path": "/w8vjLqIaNCHtbPiGWKFYlKP3ueM.jpg",
        "release_date": "2006-08-15",
        "title": "Robin Williams: A Family Affair",
        "video": true,
        "vote_average": 0,
        "vote_count": 0
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [],
        "id": 358274,
        "original_language": "en",
        "original_title": "A Family Affair",
        "overview": "Part of BFI collection \"Your Children and You.\" A simple film stating the need for more foster parents. Gives glimpses of the tragedy which comes to some children, how they are helped by the Boarding-Out Officer and placed in a \"short-stay\" Home until foster parents can be found.",
        "popularity": 0.001,
        "poster_path": null,
        "release_date": "1950-12-31",
        "title": "A Family Affair",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      },
      {
        "adult": false,
        "backdrop_path": "/l5Q3LcVlac6TpGsM0Zdvu9dhhc.jpg",
        "genre_ids": [35],
        "id": 899792,
        "original_language": "de",
        "original_title": "Der Nachname",
        "overview": "The Berger and Böttcher families come to Dorothea's finca on Lanzarote for a weekend trip. The mood is tense and escalates as various mysteries are revealed.",
        "popularity": 6.415,
        "poster_path": "/1kEVyDuA8g4WfPnrFhVvey3Flu2.jpg",
        "release_date": "2022-10-20",
        "title": "Family Affairs",
        "video": false,
        "vote_average": 6.6,
        "vote_count": 50
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [35, 18],
        "id": 682926,
        "original_language": "cn",
        "original_title": "清官難審",
        "overview": "Traditional values and modern ideals clash when an old-fashioned father and his playboy son cannot see eye to eye in this honest look at the sometimes fragile father, son relationship",
        "popularity": 3.429,
        "poster_path": "/jHQj6ldJkWOLcxd76XH1Jion1M2.jpg",
        "release_date": "1994-11-10",
        "title": "Family Affairs",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      },
      {
        "adult": false,
        "backdrop_path": "/ykNPMEWAyh23hf1FRK4lZ6dDyPx.jpg",
        "genre_ids": [10751, 18],
        "id": 602519,
        "original_language": "ko",
        "original_title": "니나 내나",
        "overview": "One day, three siblings receive a postcard from their mother who left them a long time ago. But all it says is \"I miss you.\" Three siblings are disconcerted by the sudden contact, but eventually, they go on a trip to meet their mother.",
        "popularity": 3.298,
        "poster_path": "/8as1yZZjVwsgH26AeKKoqJGktr0.jpg",
        "release_date": "2019-10-30",
        "title": "Family Affair",
        "video": false,
        "vote_average": 7.8,
        "vote_count": 4
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [99],
        "id": 792884,
        "original_language": "he",
        "original_title": "משפחת כולאני",
        "overview": "Family Affairs is an Israeli documentary film directed by Gil Golan, which was released in 2013. The film tells the story of Gil, a treacherous man who came from a family where infidelity has always been an integral part of the relationship. Gil embarks on a documentary journey into the depths of family history on the question of whether it is possible to break the pattern that is passed down from generation to generation.",
        "popularity": 1.605,
        "poster_path": "/qfj07QL8CkCGW10lBkkfrHWrxHx.jpg",
        "release_date": "2013-06-03",
        "title": "Family Affairs",
        "video": false,
        "vote_average": 8,
        "vote_count": 1
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [],
        "id": 828058,
        "original_language": "en",
        "original_title": "AIDS: A Family Affair",
        "overview": "A talk show format video featuring people living with AIDS and their friends and families in Toronto",
        "popularity": 0.001,
        "poster_path": "/aY4IXCA3nuSUsWNuzmN245AMVtT.jpg",
        "release_date": "1990-01-01",
        "title": "AIDS: A Family Affair",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      }
    ],
    "total_pages": 2,
    "total_results": 28
  }

console.log("movieSearch", movieSearch)
console.log("urlSearch", urlSearch)