export const urlTrending = "https://api.themoviedb.org/3/trending/movie/day?api_key=46829fa1f677f290fd75025af8b47e21"
export const trending = 
{
    "page": 1,
    "results": [
      {
        "backdrop_path": "/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg",
        "id": 786892,
        "title": "Furiosa: A Mad Max Saga",
        "original_title": "Furiosa: A Mad Max Saga",
        "overview": "As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.",
        "poster_path": "/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "en",
        "genre_ids": [28, 12, 878],
        "popularity": 4252.2,
        "release_date": "2024-05-22",
        "video": false,
        "vote_average": 7.718,
        "vote_count": 1374
      },
      {
        "backdrop_path": "/oZDRuGHhe5uY8wBqFJcJZT9kdvJ.jpg",
        "id": 1086747,
        "title": "The Watchers",
        "original_title": "The Watchers",
        "overview": "A young artist gets stranded in an extensive, immaculate forest in western Ireland, where, after finding shelter, she becomes trapped alongside three strangers, stalked by mysterious creatures each night.",
        "poster_path": "/vZVEUPychdvZLrTNwWErr9xZFmu.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "en",
        "genre_ids": [27, 9648, 14],
        "popularity": 788.005,
        "release_date": "2024-06-06",
        "video": false,
        "vote_average": 6.287,
        "vote_count": 211
      },
      {
        "backdrop_path": "/ngLxW9WqQAkTCBTcjOSt2Pnz5qZ.jpg",
        "id": 987686,
        "title": "A Family Affair",
        "original_title": "A Family Affair",
        "overview": "The only thing worse than being the assistant to a high-maintenance movie star who doesn't take you seriously? Finding out he's smitten with your mom.",
        "poster_path": "/l0CaVyqnTsWwNd4hWsrLNEk1Wjd.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "en",
        "genre_ids": [10749, 35],
        "popularity": 172.586,
        "release_date": "2024-06-27",
        "video": false,
        "vote_average": 6.487,
        "vote_count": 38
      },
      {
        "backdrop_path": "/75nSb1fbWooipwcSU5bUttiOriI.jpg",
        "id": 508883,
        "title": "The Boy and the Heron",
        "original_title": "君たちはどう生きるか",
        "overview": "While the Second World War rages, the teenage Mahito, haunted by his mother's tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy's mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the \"long-awaited one.\"",
        "poster_path": "/jDQPkgzerGophKRRn7MKm071vCU.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "ja",
        "genre_ids": [16, 12, 14],
        "popularity": 418.17,
        "release_date": "2023-07-14",
        "video": false,
        "vote_average": 7.462,
        "vote_count": 1316
      },
      {
        "backdrop_path": "/1XyIHrP7X7rn3UBkNy9hPb9vCUf.jpg",
        "id": 762441,
        "title": "A Quiet Place: Day One",
        "original_title": "A Quiet Place: Day One",
        "overview": "As New York City is invaded by alien creatures who hunt by sound, a woman named Sammy fights to survive.",
        "poster_path": "/yrpPYKijwdMHyTGIOd1iK1h0Xno.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "en",
        "genre_ids": [27, 878, 53, 18],
        "popularity": 967.527,
        "release_date": "2024-06-26",
        "video": false,
        "vote_average": 7.092,
        "vote_count": 92
      },
      {
        "backdrop_path": "/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg",
        "id": 1022789,
        "title": "Inside Out 2",
        "original_title": "Inside Out 2",
        "overview": "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
        "poster_path": "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "en",
        "genre_ids": [16, 10751, 12, 35],
        "popularity": 5142.888,
        "release_date": "2024-06-11",
        "video": false,
        "vote_average": 7.754,
        "vote_count": 1043
      },
      {
        "backdrop_path": "/2oTqxCe7EGMqMpJx5we2xcBT6Lx.jpg",
        "id": 1058617,
        "title": "Fancy Dance",
        "original_title": "Fancy Dance",
        "overview": "Following her sister's disappearance, Jax and her niece Roki must stick together. Desperate to keep what's left of their family intact, Jax and Roki defy the law and hit the road on a journey to the Grand Nation Powwow in Oklahoma City.",
        "poster_path": "/uEiosO6QiXITDIMGf2JQ9tRkqyM.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "en",
        "genre_ids": [18],
        "popularity": 25.41,
        "release_date": "2024-06-21",
        "video": false,
        "vote_average": 7.6,
        "vote_count": 4
      },
      {
        "backdrop_path": "/h7V8yzSnPYkNEvAqmeYHcfJ6rbk.jpg",
        "id": 1214509,
        "title": "In a Violent Nature",
        "original_title": "In a Violent Nature",
        "overview": "The enigmatic resurrection, rampage, and retribution of an undead monster in a remote wilderness unleashes an iconic new killer after a locket is removed from a collapsed fire tower that entombed its rotting corpse.",
        "poster_path": "/o5pcDZaA9Up0X612os34JNCRX6j.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "en",
        "genre_ids": [27, 53],
        "popularity": 48.178,
        "release_date": "2024-05-31",
        "video": false,
        "vote_average": 6,
        "vote_count": 15
      },
      {
        "backdrop_path": "/24r8W0t5ZR9FYF5MvtzFeUa2gmL.jpg",
        "id": 1291559,
        "title": "Drawing Closer",
        "original_title": "余命一年の僕が、余命半年の君と出会った話。",
        "overview": "With only a year left to live, 17-year-old Akito finds new meaning in life by bringing joy to a terminally ill girl who has just six months remaining.",
        "poster_path": "/173FD4a0rpSF30z4CoWx6qdx8Ry.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "ja",
        "genre_ids": [10749, 18],
        "popularity": 63.951,
        "release_date": "2024-06-27",
        "video": false,
        "vote_average": 7.5,
        "vote_count": 4
      },
      {
        "backdrop_path": "/nxxCPRGTzxUH8SFMrIsvMmdxHti.jpg",
        "id": 639720,
        "title": "IF",
        "original_title": "IF",
        "overview": "A young girl who goes through a difficult experience begins to see everyone's imaginary friends who have been left behind as their real-life friends have grown up.",
        "poster_path": "/xbKFv4KF3sVYuWKllLlwWDmuZP7.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "en",
        "genre_ids": [35, 14, 10751],
        "popularity": 900.59,
        "release_date": "2024-05-08",
        "video": false,
        "vote_average": 7.426,
        "vote_count": 465
      },
      {
        "backdrop_path": "/fDmci71SMkfZM8RnCuXJVDPaSdE.jpg",
        "id": 519182,
        "title": "Despicable Me 4",
        "original_title": "Despicable Me 4",
        "overview": "Gru and Lucy and their girls — Margo, Edith and Agnes — welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, and the family is forced to go on the run.",
        "poster_path": "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "en",
        "genre_ids": [16, 10751, 35, 28],
        "popularity": 893.728,
        "release_date": "2024-06-20",
        "video": false,
        "vote_average": 8.6,
        "vote_count": 57
      },
      {
        "backdrop_path": "/aATi2PtaOQCVAquCym6OU0Z4FjY.jpg",
        "id": 704673,
        "title": "Trigger Warning",
        "original_title": "Trigger Warning",
        "overview": "A Special Forces commando uncovers a dangerous conspiracy when she returns to her hometown looking for answers into her beloved father's death.",
        "poster_path": "/3Upk7iUi5cIsDJm5QlnzaHILHN8.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "en",
        "genre_ids": [28, 80, 53],
        "popularity": 1003.673,
        "release_date": "2024-06-20",
        "video": false,
        "vote_average": 5.7,
        "vote_count": 187
      },
      {
        "backdrop_path": "/jvPMJ2zM92jfXxVEFsqP1MMrLaO.jpg",
        "id": 823464,
        "title": "Godzilla x Kong: The New Empire",
        "original_title": "Godzilla x Kong: The New Empire",
        "overview": "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
        "poster_path": "/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "en",
        "genre_ids": [878, 28, 12],
        "popularity": 1248.903,
        "release_date": "2024-03-27",
        "video": false,
        "vote_average": 7.218,
        "vote_count": 2948
      },
      {
        "backdrop_path": "/dvBCdCohwWbsP5qAaglOXagDMtk.jpg",
        "id": 533535,
        "title": "Deadpool & Wolverine",
        "original_title": "Deadpool & Wolverine",
        "overview": "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
        "poster_path": "/jbwYaoYWZwxtPP76AZnfYKQjCEB.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "en",
        "genre_ids": [878, 28, 35],
        "popularity": 323.18,
        "release_date": "2024-07-24",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      },
      {
        "backdrop_path": "/1r1dWa9yf1LeSLfkOfkSqxmWHdK.jpg",
        "id": 967847,
        "title": "Ghostbusters: Frozen Empire",
        "original_title": "Ghostbusters: Frozen Empire",
        "overview": "When the discovery of an ancient artifact unleashes an evil force, Ghostbusters new and old must join forces to protect their home and save the world from a second Ice Age.",
        "poster_path": "/e1J2oNzSBdou01sUvriVuoYp0pJ.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "en",
        "genre_ids": [14, 12, 35],
        "popularity": 292.799,
        "release_date": "2024-03-20",
        "video": false,
        "vote_average": 6.703,
        "vote_count": 1047
      },
      {
        "backdrop_path": "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
        "id": 693134,
        "title": "Dune: Part Two",
        "original_title": "Dune: Part Two",
        "overview": "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
        "poster_path": "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "en",
        "genre_ids": [878, 12],
        "popularity": 494.913,
        "release_date": "2024-02-27",
        "video": false,
        "vote_average": 8.167,
        "vote_count": 4685
      },
      {
        "backdrop_path": "/j29ekbcLpBvxnGk6LjdTc2EI5SA.jpg",
        "id": 150540,
        "title": "Inside Out",
        "original_title": "Inside Out",
        "overview": "When 11-year-old Riley moves to a new city, her Emotions team up to help her through the transition. Joy, Fear, Anger, Disgust and Sadness work together, but when Joy and Sadness get lost, they must journey through unfamiliar places to get back home.",
        "poster_path": "/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "en",
        "genre_ids": [16, 10751, 12, 18, 35],
        "popularity": 1595.877,
        "release_date": "2015-06-17",
        "video": false,
        "vote_average": 7.915,
        "vote_count": 20933
      },
      {
        "backdrop_path": "/lOKQYk0IHZ3U6y1USV8dL3StXaE.jpg",
        "id": 801688,
        "title": "Kalki 2898 - AD",
        "original_title": "కల్కి 2898 - ఎ.డి",
        "overview": "Bhairava, tired of the oppressive confines of his homeland and the perilous life of a bounty hunter, yearns for a more comfortable existence in the Complex. His quest for a new life inadvertently entangles him with a group of rebels dedicated to freeing humanity from the grip of malevolent forces.",
        "poster_path": "/zNE88KjSX2nDSWjdsNqeIFGAXo8.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "te",
        "genre_ids": [18, 28, 14, 878],
        "popularity": 203.135,
        "release_date": "2024-06-26",
        "video": false,
        "vote_average": 7.7,
        "vote_count": 9
      },
      {
        "backdrop_path": "/z121dSTR7PY9KxKuvwiIFSYW8cf.jpg",
        "id": 929590,
        "title": "Civil War",
        "original_title": "Civil War",
        "overview": "In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.",
        "poster_path": "/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "en",
        "genre_ids": [10752, 28, 18],
        "popularity": 1088.85,
        "release_date": "2024-04-10",
        "video": false,
        "vote_average": 7.006,
        "vote_count": 1739
      },
      {
        "backdrop_path": "/gqrnQA6Xppdl8vIb2eJc58VC1tW.jpg",
        "id": 76341,
        "title": "Mad Max: Fury Road",
        "original_title": "Mad Max: Fury Road",
        "overview": "An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and most everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order.",
        "poster_path": "/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
        "media_type": "movie",
        "adult": false,
        "original_language": "en",
        "genre_ids": [28, 12, 878],
        "popularity": 434.482,
        "release_date": "2015-05-13",
        "video": false,
        "vote_average": 7.603,
        "vote_count": 21981
      }
    ],
    "total_pages": 1000,
    "total_results": 20000
}

